name: PR Checks

# Run checks that ensure code quality of pull requests

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    name: Check Lua
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Lua
      uses: nebularg/actions-luacheck@v1
      with:
        args: ItemVersion --no-color --exclude-files 'ItemVersion/Libs/**/*.lua' --no-self
